version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:80"
    #volumes:
     # - ./app:/app
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "TuContraseña1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

